#!/usr/bin/env node
// Regenerates src/plugins/index.js from the PLUGINS env var — a
// comma-separated list of c2c-plugins registry names to bundle (default,
// or the literal "all", bundles everything). Runs automatically before
// `npm run dev`/`npm run build`/`npm test` (see package.json's pre* scripts)
// so the checked-in src/plugins/index.js is always regenerated fresh before
// use; it's still committed so the repo isn't left with a missing/stale
// file for anyone who reads it without running a script first.
//
// Only static per-plugin imports achieve real bundle-size exclusion — a
// runtime filter over an eagerly-imported registry would still pull every
// plugin's code into the graph Rollup sees, dynamic-import chunks included.
// So this writes the exact set of import statements a given PLUGINS
// selection needs, rather than filtering an already-fully-imported list.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { REGISTRY, INPUT_REGISTRY } from "c2c-plugins";

const allNames = Object.keys(REGISTRY);
const raw = (process.env.PLUGINS || "").trim();
const requested = !raw || raw === "all" ? allNames : raw.split(",").map((s) => s.trim()).filter(Boolean);

const unknown = requested.filter((name) => !REGISTRY[name]);
if (unknown.length) {
  console.error(
    `select-plugins: unknown plugin name(s) in PLUGINS: ${unknown.join(", ")}.\n` +
    `Known plugins: ${allNames.join(", ")}`
  );
  process.exit(1);
}

// Preserve REGISTRY's own order (hook-execution order for plugins sharing a
// stage — see c2c-plugins/index.js) rather than the order PLUGINS listed
// them in.
const selected = allNames.filter((name) => requested.includes(name));

const importLines = selected.map(
  (name, i) => `import { createPlugin as create_${i} } from "c2c-plugins/src/${name}/index.js";`
);
const pluginLines = selected.map((name, i) => `  create_${i}(deps), // ${name}`);

const inputModes = Object.keys(INPUT_REGISTRY); // always all — mutually exclusive, small, needed for UI mode-switching
const inputImportLines = inputModes.map(
  (mode, i) => `import { createPlugin as createInput_${i} } from "c2c-plugins/src/${mode === "generic" ? "generic-input" : "docx-input"}/index.js";`
);
const inputPluginLines = inputModes.map((mode, i) => `  ${mode}: createInput_${i}(deps),`);

const body = `// AUTO-GENERATED by scripts/select-plugins.mjs from the PLUGINS env var —
// do not edit by hand, your changes will be overwritten. Regenerated by the
// pretest/predev/prebuild npm hooks; run \`node scripts/select-plugins.mjs\`
// directly to regenerate without also running dev/build/test.
// Selected plugins (PLUGINS=${raw || "all"}): ${selected.join(", ") || "(none)"}
import { buildDeps } from "./deps.js";
${importLines.join("\n")}
${inputImportLines.join("\n")}

const deps = buildDeps();

// Order here is hook-execution order for plugins sharing a hook stage
// (createHookBus's priority defaults to 10 for every registration, and
// Array#sort is stable, so registration order reproduces the original
// processFolder sequence — see c2c-plugins/index.js's REGISTRY ordering).
export const PLUGINS = [
${pluginLines.join("\n")}
];

// Input-mode plugins are a separate registry from PLUGINS above: they're
// mutually exclusive (exactly one runs per build, dispatched by
// pipeline.js on ctx.options.inputMode), not additive hook taps that all
// coexist — so they don't go through registerAllPlugins/composeOptionSchema.
export const INPUT_PLUGINS = {
${inputPluginLines.join("\n")}
};

export function registerAllPlugins(hookBus, plugins = PLUGINS) {
  for (const plugin of plugins) {
    for (const [hookName, handler] of Object.entries(plugin.hooks || {})) {
      hookBus.on(hookName, handler, { pluginName: plugin.name });
    }
  }
}

export function composeOptionSchema(plugins = PLUGINS) {
  return plugins.map((p) => p.optionSchema).filter(Boolean);
}

export function composeSettingsSchema(plugins = PLUGINS) {
  return plugins.map((p) => p.settingsSchema).filter(Boolean);
}
`;

const outPath = fileURLToPath(new URL("../src/plugins/index.js", import.meta.url));
writeFileSync(outPath, body);
console.log(`select-plugins: wrote src/plugins/index.js — ${selected.length}/${allNames.length} plugin(s): ${selected.join(", ") || "(none)"}`);
