// AUTO-GENERATED by scripts/select-plugins.mjs from the PLUGINS env var —
// do not edit by hand, your changes will be overwritten. Regenerated by the
// pretest/predev/prebuild npm hooks; run `node scripts/select-plugins.mjs`
// directly to regenerate without also running dev/build/test.
// Selected plugins (PLUGINS=all): xlsx-crate-input, austlang, ca-data-prep, merge, validate-crate, ro-crate-json-output, ro-crate-xlsx-output, ro-crate-html-output
// Selected input modes (INPUT_PLUGINS=generic,docx): generic, docx
import { buildDeps } from "./deps.js";
import { createPlugin as create_0 } from "c2c-plugins/src/xlsx-crate-input/index.js";
import { createPlugin as create_1 } from "c2c-plugins/src/austlang/index.js";
import { createPlugin as create_2 } from "c2c-plugins/src/ca-data-prep/index.js";
import { createPlugin as create_3 } from "c2c-plugins/src/merge/index.js";
import { createPlugin as create_4 } from "c2c-plugins/src/validate-crate/index.js";
import { createPlugin as create_5 } from "c2c-plugins/src/ro-crate-json-output/index.js";
import { createPlugin as create_6 } from "c2c-plugins/src/ro-crate-xlsx-output/index.js";
import { createPlugin as create_7 } from "c2c-plugins/src/ro-crate-html-output/index.js";
import { createPlugin as createInput_0 } from "c2c-plugins/src/generic-input/index.js";
import { createPlugin as createInput_1 } from "c2c-plugins/src/docx-input/index.js";

const deps = buildDeps();

// Order here is hook-execution order for plugins sharing a hook stage
// (createHookBus's priority defaults to 10 for every registration, and
// Array#sort is stable, so registration order reproduces the original
// processFolder sequence — see c2c-plugins/index.js's REGISTRY ordering).
// Plugins from a custom source (name=package or name=./path.js in PLUGINS)
// are appended after the c2c-plugins ones, in the order they were listed —
// this script has no way to know where they should sit relative to others
// sharing a hook stage, so place them in PLUGINS accordingly if that matters.
export const PLUGINS = [
  create_0(deps), // xlsx-crate-input
  create_1(deps), // austlang
  create_2(deps), // ca-data-prep
  create_3(deps), // merge
  create_4(deps), // validate-crate
  create_5(deps), // ro-crate-json-output
  create_6(deps), // ro-crate-xlsx-output
  create_7(deps), // ro-crate-html-output
];

// Input-mode plugins are a separate registry from PLUGINS above: they're
// mutually exclusive (exactly one runs per build, dispatched by
// pipeline.js on ctx.options.inputMode), not additive hook taps that all
// coexist — so they don't go through registerAllPlugins/composeOptionSchema.
export const INPUT_PLUGINS = {
  generic: createInput_0(deps),
  docx: createInput_1(deps),
};

export function registerAllPlugins(hookBus, plugins = PLUGINS) {
  for (const plugin of plugins) {
    for (const [hookName, handler] of Object.entries(plugin.hooks || {})) {
      hookBus.on(hookName, handler, { pluginName: plugin.name });
    }
  }
}

export function composeOptionSchema(plugins = PLUGINS) {
  return plugins.map((p) => p.optionSchema).filter(Boolean);
}

export function composeSettingsSchema(plugins = PLUGINS) {
  return plugins.map((p) => p.settingsSchema).filter(Boolean);
}
