// AUTO-GENERATED by scripts/select-plugins.mjs from the PLUGINS env var —
// do not edit by hand, your changes will be overwritten. Regenerated by the
// pretest/predev/prebuild npm hooks; run `node scripts/select-plugins.mjs`
// directly to regenerate without also running dev/build/test.
// Selected plugins (PLUGINS=all): xlsx-crate-input, austlang, file-format-identify, ca-data-prep, chat-export, merge, crate2tables, validate-crate, ro-crate-json-output, ro-crate-xlsx-output, ro-crate-html-output
// Selected input modes (INPUT_PLUGINS=generic,docx): generic, docx
import { buildDeps } from "./deps.js";
import { createPlugin as create_0 } from "c2c-plugins/src/xlsx-crate-input/index.js";
import { createPlugin as create_1 } from "c2c-plugins/src/austlang/index.js";
import { createPlugin as create_2 } from "c2c-plugins/src/file-format-identify/index.js";
import { createPlugin as create_3 } from "c2c-plugins/src/ca-data-prep/index.js";
import { createPlugin as create_4 } from "c2c-plugins/src/chat-export/index.js";
import { createPlugin as create_5 } from "c2c-plugins/src/merge/index.js";
import { createPlugin as create_6 } from "c2c-plugins/src/crate2tables/index.js";
import { createPlugin as create_7 } from "c2c-plugins/src/validate-crate/index.js";
import { createPlugin as create_8 } from "c2c-plugins/src/ro-crate-json-output/index.js";
import { createPlugin as create_9 } from "c2c-plugins/src/ro-crate-xlsx-output/index.js";
import { createPlugin as create_10 } from "c2c-plugins/src/ro-crate-html-output/index.js";
import { createPlugin as createInput_0 } from "c2c-plugins/src/generic-input/index.js";
import { createPlugin as createInput_1 } from "c2c-plugins/src/docx-input/index.js";

const deps = buildDeps();

// Order here is hook-execution order for plugins sharing a hook stage
// (createHookBus's priority defaults to 10 for every registration, and
// Array#sort is stable, so registration order reproduces the original
// processFolder sequence — see c2c-plugins/index.js's REGISTRY ordering).
// Plugins from a custom source (name=package or name=./path.js in PLUGINS)
// are appended after the c2c-plugins ones, in the order they were listed —
// this script has no way to know where they should sit relative to others
// sharing a hook stage, so place them in PLUGINS accordingly if that matters.
export const PLUGINS = [
  create_0(deps), // xlsx-crate-input
  create_1(deps), // austlang
  create_2(deps), // file-format-identify
  create_3(deps), // ca-data-prep
  create_4(deps), // chat-export
  create_5(deps), // merge
  create_6(deps), // crate2tables
  create_7(deps), // validate-crate
  create_8(deps), // ro-crate-json-output
  create_9(deps), // ro-crate-xlsx-output
  create_10(deps), // ro-crate-html-output
];

// Input-mode plugins are a separate registry from PLUGINS above: they're
// mutually exclusive (exactly one runs per build, dispatched by
// pipeline.js on ctx.options.inputMode), not additive hook taps that all
// coexist — so they don't go through registerAllPlugins/composeOptionSchema.
export const INPUT_PLUGINS = {
  generic: createInput_0(deps),
  docx: createInput_1(deps),
};

export function registerAllPlugins(hookBus, plugins = PLUGINS) {
  for (const plugin of plugins) {
    for (const [hookName, handler] of Object.entries(plugin.hooks || {})) {
      hookBus.on(hookName, handler, { pluginName: plugin.name });
    }
  }
}

export function composeOptionSchema(plugins = PLUGINS) {
  return plugins.map((p) => p.optionSchema).filter(Boolean);
}

export function composeSettingsSchema(plugins = PLUGINS) {
  return plugins.map((p) => p.settingsSchema).filter(Boolean);
}

// Every file/directory a registered plugin may write directly into the
// picked folder — additive plugins and input-mode plugins alike, since both
// write into the same folder and a build can switch between input modes on
// a folder that still holds a previous run's output. Deduped by path (e.g.
// chat-export and ca-data-prep both declare "c2c-output"), first declared
// kind wins. Consumed by main.js for two things: excluding this from the
// next scan (alongside GENERATED_FILENAMES/CONTROL_FILENAMES) and the
// "delete plugin output before rebuilding" setting.
export function composeOutputPaths(plugins = PLUGINS, inputPlugins = INPUT_PLUGINS) {
  const byPath = new Map();
  for (const plugin of [...plugins, ...Object.values(inputPlugins)]) {
    for (const entry of plugin.outputPaths || []) {
      if (!byPath.has(entry.path)) byPath.set(entry.path, entry);
    }
  }
  return [...byPath.values()];
}
